% reads verified mmts file
function [output] = read_mmts(path, mode_)
    arguments
        path string
        mode_ int = 1
    end
    output = readtable( ...
        fullfile("Data", "Mode_"+mode_,  path+'+.mmts'), ...
        FileType='text', ...
        VariableNamingRule='preserve' ...
    );
end